### ISSUE TITLE
Support for python 2

### ISSUE THREAD

**Issue by ddeath** [triaxtec/openapitools-generator-action#14]
Would it be possible to add support for python 2?

Current version throws syntax error because of this line:
https://github.com/openapi-generators/openapitools-generator-action/blob/v1/entrypoint.py#L5

Python 2 do not supports varargs in unpacking

**Comment by ddeath** [comment]
Created PR if we want to support this https://github.com/openapi-generators/openapitools-generator-action/pull/15

**Comment by dbanty** [comment]
For my own understanding, what's the use-case of needing this action to support Python 2? Is there some interference with other CI tools? I had assumed that code generation would mostly be its own job.

**Comment by ddeath** [comment]
The issue is that you can have your own Github Action runner for example on ec2 where is totally different env from what are default Github Runners using... Anyway... This PR is still not working yet, looks like python 2 does not allow file access or something, still debugging... I will probably just remove that python script and replace it with bash script which should be more portable

**Comment by ddeath** [comment]
Closing this as probably there will be no interest for this feature in wider audience... we will just support it in our fork
