### ISSUE TITLE
Support for giving a non-relative file paths

### ISSUE THREAD

**Issue by maverick1872** [triaxtec/openapitools-generator-action#16]
Would be really convenient to support non-relative file paths for things like the openapi json spec. This is because I download the json document and the `download-artifact` action gives me an output to where it downloads files. As such, it would make dealing with file paths much easier to determine what's most appropriate.

Edit: Additionally is there anyway to see the file dir structure that the generator action sees? Would be easier to debug file path issues. Happy to open a draft PR sometime if there's interest.

**Comment by dbanty** [comment]
All set! If you provide a path starting with `/`, it will now be considered an absolute path and not prepended with `/github/workspace/`. I don't know exactly what directories the action will have access to, so it still might take some experimenting to get it to work just right.

**Comment by maverick1872** [comment]
Thanks so much! I'll let ya know if I run into any issues.
