### ISSUE TITLE
Can not run github action

### ISSUE THREAD

**Issue by wirthual** [triaxtec/openapitools-generator-action#9]
Hello,

thank you for this helpful action. 

When I try to run it I get the following error:
```
Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
[main] ERROR o.o.c.config.CodegenConfigurator - /github/workspace (Is a directory)
[main] ERROR o.o.c.config.CodegenConfigurator - /github/workspace (Is a directory)
Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: /github/workspace/
	at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:155)
	at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:86)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:272)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Error: Process completed with exit code 1.
```

This is the repo I am trying to use it for: https://github.com/wirthual/autobahn-api

with this action: https://github.com/wirthual/autobahn-api/blob/main/.github/workflows/openapi_check.yaml

And here the spec file: https://github.com/wirthual/autobahn-api/blob/main/openapi.yaml

Also tested to use openapi-file and point it to openapi.yaml directly. Also not successful. Am I missing something?

**Comment by dbanty** [comment]
Hmm, I'm not sure. The one thing I notice is that you aren't pointing at a config file, but the action currently has it as required. I don't think it's actually required by the generator, so I'll try to make it optional and see if that fixes things.

**Comment by dbanty** [comment]
Should be all fixed in 1.1.1, thanks for reporting!

**Comment by wirthual** [comment]
Thank you for taking care of this :) 

I will check if I can run it now without specifing the config. 

For a test I added a config file which changes the name of the package and now I get this error:

https://github.com/wirthual/autobahn-api/runs/4057345349?check_suite_focus=true

```
Run openapi-generators/openapitools-generator-action@v1
Run python /home/runner/work/_actions/openapi-generators/openapitools-generator-action/v1/entrypoint.py  latest openapi.yaml UNSET generator_config.yaml
Traceback (most recent call last):
  File "/home/runner/work/_actions/openapi-generators/openapitools-generator-action/v1/entrypoint.py", line 5, in <module>
    (_, generator, generator_tag, openapi_file, openapi_url, config_file) = argv
ValueError: not enough values to unpack (expected 6, got 5)
Error: Process completed with exit code 1.
```

Will further investigate on my side if I am missing something.

**Comment by dbanty** [comment]
Looks like you also need to specify the `generator` option so it knows which generator to run.

**Comment by wirthual** [comment]
Oh yes thats correct. Its working now. Thank you for the hint!

I switched between  openapi-python-client-action and  openapitools-generator-action and forgot to put the key back in.
